sudo: required

services:
  - docker

language: c

script:
  - docker pull ubuntu:latest
  - docker run --name ubuntu --workdir $TRAVIS_BUILD_DIR ubuntu:latest bash
  - docker exec ubuntu apt-get update
  - docker exec ubuntu apt-get install -y --no-install-recommends gtk-doc-tools intltool libaudit-dev libgcrypt20-dev libgirepository1.0-dev libglib2.0-dev libgtk-3-dev libpam0g-dev libqt4-dev libxcb1-dev libxdmcp-dev libxklavier-dev qtbase5-dev valac yelp-tools
  - docker exec ubuntu ./autogen.sh && make
